#!/usr/bin/env python

import os
import sys
import subprocess

maven_repo_dir = os.path.dirname(os.path.realpath(__file__))
optional_args = sys.argv[1:]

subprocess.call(['mvn', '-Ddeploy.path=' + maven_repo_dir, 'clean', 'deploy'] + optional_args)